### ISSUE TITLE
is there any memory release method in sound? i played 100 sounds in my game.memory inscrease by 1 mb

### ISSUE THREAD

**Issue by baifan233** [Tama-sama/AudioPlayer#2]
how do i release those played sounds

**Comment by CuriousTama** [comment]
Hellow, sorry for the inconvenience that have cause for you, after quickly looking back at the code, there is no clear unmanaged allocation to the heap, I don't say that impossible that a memory leak is present.

I need more information from you, for example, what extension of sound did you play ? Is it when you play or add a sound ? Did you look at the memory diagnostic tool, is it when you play (with/without new object creation) ? Etc…  
 
Note: I plan to probably refacto this library in some months

**Comment by baifan233** [comment]
thanks for your library,i did learn things from it.
you can try in your 
void example(string SoundPath) func in your example.cpp

set the  looping to false Emitter.setLooping(false);

and add a loop to play to  suppose i have the same sound to play in different time point

float memory1=GetMem();
for (size_t i = 0; i < 100; i++)
{
	Emitter.play(); 
	Sleep(100);
}
float memory2=GetMem();

after a few minuates
the memory still holds to memory2,but not turn back to memory1

**Comment by CuriousTama** [comment]
Thanks for your interest in this piece of code, even if you learned things be careful there are also some bad practices in there, of which my intention to make a refacto of this code. This code when I didn't have much experience.

After investigating I think I found the "issue", there is a buffer of allocation that will be reused when inactive, I guess I could clean them better before inactivating them and let the possibility to clean them with a method. 

In the end it's not a true memory leak, but it can be improved, I will do that when refactoring the code, I guess I will work on it sooner than I expected to.

**Comment by CuriousTama** [comment]
Now with the new rework it should not be any problem like this one, there is only ~1mb when playing the first sound because of the xAudio2, it can't be cleared (not that I've found), when a sound stop it is well released.
PS : (Sorry the rework is not backward compatible)
